<?php
/**
 */

namespace execut\seo\crudFields;
use execut\crudFields\fields\HasManyMultipleInput;
use execut\crudFields\fields\HasManySelect2;
use execut\seo\models\Keyword;
use execut\seo\models\KeywordVsPage;
use yii\helpers\Inflector;

class Keywords extends \execut\crudFields\Plugin
{
    public function getFields() {

        return [
            [
                'class' => HasManyMultipleInput::class,
                'attribute' => 'seoKeywords',
                'relation' => 'seoKeywords',
                'url' => [
                    '/seo/keywords'
                ],
            ],
        ];
    }
    
    public function getRelations()
    {
        return [
            'seoKeywords' => [
               'class' => Keyword::class,
               'name' => 'seoKeywords',
               'link' => [
                   'id' => 'seo_keyword_id',
               ],
                'via' => 'vsSeoKeywords',
//                'viaTable' => 'seo_keywords_vs_' . $this->getOwnerTableName(),
//                'viaLink' => [
//                    'seo_keyword_id' => 'id',
//                ],
                'multiple' => true
            ],
            'vsSeoKeywords' => [
                'class' => KeywordVsPage::class,
                'name' => 'vsSeoKeywords',
                'link' => [
                    'pages_page_id' => 'id',
                ],
                'multiple' => true
            ],
        ]; // TODO: Change the autogenerated stub
    }

    protected function getOwnerTableName() {
        return $this->owner->tableName();
    }

    protected function getOwnerForeignKey() {
        $tableName = $this->getOwnerTableName();

        return Inflector::singularize($tableName) . '_id';
    }
}