<?php
/**
 */

namespace execut\seo\bootstrap;


use execut\seo\FieldsAttacher;
use execut\seo\KeywordsAttacher;
use execut\seo\Module;
use execut\yii\Bootstrap;

class Common extends Bootstrap
{
    public $_defaultDepends = [
        'modules' => [
            'seo' => [
                'class' => Module::class,
            ],
        ],
    ];
    public function bootstrap($app)
    {
        parent::bootstrap($app); // TODO: Change the autogenerated stub
        $module = \yii::$app->getModule('seo');
        $models = $module->getKeywordsModels();
        $tables = $this->getModelsTables($models);

        $helper = new KeywordsAttacher([
            'tables' => $tables,
        ]);
        $helper->up();

        $models = $module->getFieldsModels();
        $tables = $this->getModelsTables($models);
        $helper = new FieldsAttacher([
            'tables' => $tables,
        ]);
        $helper->up();
    }

    /**
     * @param $models
     * @return array
     */
    protected function getModelsTables($models)
    {
        $tables = [];
        foreach ($models as $model) {
            $tables[] = $model::tableName();
        }
        return $tables;
    }
}